package gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import piece.Alliance;
import timer.TimeControl;

import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class ClocksHolderPanel extends javax.swing.JPanel {

    ClockPanel whiteClock;
    ClockPanel blackClock;

    public ClocksHolderPanel() {

        whiteClock = new ClockPanel(Alliance.WHITE, new TimeControl(0,5,3,2));
        blackClock = new ClockPanel(Alliance.BLACK, new TimeControl(0,5,3,2));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        whiteClockPanel = new JPanel();
        blackClockPanel = new JPanel();
        notationPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(350, 600));

        javax.swing.GroupLayout blackClockPanelLayout = new javax.swing.GroupLayout(blackClockPanel);
        blackClockPanel.setLayout(blackClockPanelLayout);
        blackClockPanelLayout.setHorizontalGroup(
                blackClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        blackClockPanelLayout.setVerticalGroup(
                blackClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 137, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout whiteClockPanelLayout = new javax.swing.GroupLayout(whiteClockPanel);
        whiteClockPanel.setLayout(whiteClockPanelLayout);
        whiteClockPanelLayout.setHorizontalGroup(
                whiteClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 330, Short.MAX_VALUE)
        );
        whiteClockPanelLayout.setVerticalGroup(
                whiteClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 103, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout notationPanelLayout = new javax.swing.GroupLayout(notationPanel);
        notationPanel.setLayout(notationPanelLayout);
        notationPanelLayout.setHorizontalGroup(
                notationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        notationPanelLayout.setVerticalGroup(
                notationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 326, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(blackClockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(whiteClockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(notationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(whiteClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blackClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                blackClockPanel.add(blackClock);
                whiteClockPanel.add(whiteClock);
                validate();
                repaint();
            }
        });
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel blackClockPanel;
    private javax.swing.JPanel notationPanel;
    private javax.swing.JPanel whiteClockPanel;
    // End of variables declaration
}

